version: '3'
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    volumes: 
      - /Users/a1liltnr/Desktop/gitproject/frontend/node_modules
      - .:/app
     
    